name: hello
version: 0.1.2
synopsis: Hello
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2017-2024 Athae Eredh Siniath and Others
license: MIT
tested-with: GHC == 9.2.8

ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
  - base
  - core-data
  - core-text >= 0.3.8
  - core-program >= 0.7.0

executables:
  hello:
    source-dirs:
      - src
    main: HelloMain.hs
    ghc-options:
    - -threaded
    other-modules: []

tests:
  check:
    dependencies:
      - hspec
    ghc-options: -threaded
    source-dirs:
      - tests
    main: TestSuite.hs
    other-modules: []
