resolver: lts-18.6
packages:
 - .

#
# there was actually no immediate reason to depend on the latest versions of
# these libraries other than to show the way you add specific versions to your
# Stack resolver if you need something newer than what is in the snaphot above.
#

extra-deps:
 - core-text-0.3.2.0
 - core-data-0.2.1.9
 - core-program-0.2.9.1
