name: Check
on:
  pull_request:

jobs:
  build:
      name: Build and Test
      runs-on: ubuntu-latest
      steps:
        - name: Install Stack
          run: |
            mkdir -p ~/.local/bin
            curl -sSL https://github.com/commercialhaskell/stack/releases/download/v2.7.3/stack-2.7.3-linux-x86_64.tar.gz \
                | tar -x -z -C ~/.local/bin --strip-components=1 --wildcards '*stack'

        - name: Clone project
          uses: actions/checkout@v2

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.stack
            key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
            restore-keys: ${{ runner.os }}-

        - name: Setup GHC
          run: |
            stack setup

        - name: Build sources
          run: |
            stack build

        - name: Run tests
          run: |
            stack test
            echo "PATH=$PATH"
            ls ~/.local/bin
