name: Check
on:
  push:

jobs:
  build:
      name: Build and Test
      runs-on: ubuntu-latest
      steps:
        - name: Setup GHC
          uses: haskell/actions/setup@v1.2
          with:
            enable-stack: true
            stack-no-global: true
            stack-setup-ghc: true
            ghc-version: '8.10.7'
            stack-version: '2.7.3'

        - name: Clone project
          uses: actions/checkout@v2

        - name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.stack
            key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
            restore-keys: ${{ runner.os }}-

        - name: Build sources
          run: "stack build"

        - name: Run tests
          run: "stack test"
